image: golang:1.18-alpine

definitions:
  steps:
    - step: &check-deps
        name: "check dependencies"
        script:
          - set -e
          - go mod tidy && go mod vendor
          - git diff --exit-code -- go.mod go.sum
    - step: &build
        name: "build binaries"
        script:
          - apk add make
          - go mod download
          - make build
        artifacts: 
          - ./dist/**
pipelines:
  pull-requests:
    '**':
      - step: *check-deps
  branches:
    master:
      - step: *build
